# Generated by Django 4.1.5 on 2023-02-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_toal_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vote_toal',
            new_name='vote_total',
        ),
    ]
